//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Cascade.Data.Models
{
    public partial class MSI_ResaleRestriction
    {
        public int ID { get; set; }
        public Nullable<int> Value { get; set; }
        public string Restriction { get; set; }
    }
    
}
