//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_MessageNotification
    {
        public System.Guid Id { get; set; }
        public string Body { get; set; }
        public string Subject { get; set; }
        public Nullable<System.Guid> RecipientUserId { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
