//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_RecallForm
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OrigAcct { get; set; }
        public string AcctName { get; set; }
        public string Portfolio { get; set; }
        public string CurrentResp { get; set; }
        public string RecallReason { get; set; }
        public Nullable<System.DateTime> DateNoteSent { get; set; }
        public string PIMSAcct { get; set; }
        public string NewStatus { get; set; }
        public string NewResp { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string CheckNumber { get; set; }
        public string Invoice { get; set; }
        public string Explanation { get; set; }
        public Nullable<decimal> FaceValueofAcct { get; set; }
        public Nullable<decimal> CostBasis { get; set; }
        public Nullable<decimal> SalesBasis { get; set; }
        public string SellerCheck { get; set; }
        public Nullable<bool> Putback { get; set; }
        public Nullable<System.DateTime> DateAcctClosed { get; set; }
        public Nullable<decimal> AmtReceivable { get; set; }
        public Nullable<decimal> AmtPayable { get; set; }
        public string Seller { get; set; }
        public string GUID { get; set; }
    }
}
