//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_MediaTypes
    {
        public MSI_MediaTypes()
        {
            this.MSI_MediaRequestTypes = new HashSet<MSI_MediaRequestTypes>();
            this.MSI_MediaTracker = new HashSet<MSI_MediaTracker>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<MSI_MediaRequestTypes> MSI_MediaRequestTypes { get; set; }
        public virtual ICollection<MSI_MediaTracker> MSI_MediaTracker { get; set; }
    }
}
