//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Cascade.Data.Models
{
    public partial class MSI_vwPurchases
    {
        public string ACCOUNT { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> OriginalBalance { get; set; }
        public Nullable<decimal> purchaseprice { get; set; }
        public string Seller { get; set; }
    }
    
}
