//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_vwDebtors
    {
        public string ACCOUNT { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string ZIP { get; set; }
        public string SSN { get; set; }
        public string SS_NO { get; set; }
        public string PHONE_CELL { get; set; }
        public string PHONE_HOME { get; set; }
        public string PHONE_WORK { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> DebtCurrentBalance { get; set; }
        public Nullable<decimal> DebtorPurchaseBalance { get; set; }
        public string CreditorName { get; set; }
    }
}
