//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_MediaRequestedTypes
    {
        public System.Guid Id { get; set; }
        public System.Guid RequestedId { get; set; }
        public int TypeId { get; set; }
        public string RespondedDocuments { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.Guid> RequestedUserID { get; set; }
        public Nullable<System.Guid> RespondedUserID { get; set; }
        public Nullable<System.DateTime> RespondedDate { get; set; }
    
        public virtual MSI_MediaRequestResponse MSI_MediaRequestResponse { get; set; }
        public virtual MSI_MediaTypes MSI_MediaTypes { get; set; }
    }
}
