//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_MediaTracker
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public string OriginalAccount { get; set; }
        public Nullable<int> MediaTypeId { get; set; }
        public string MediaDocuments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TypeConstraints { get; set; }
    
        public virtual MSI_MediaTypes MSI_MediaTypes { get; set; }
    }
}
