//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_MediaRequestTypes
    {
        public string Id { get; set; }
        public string RequestedId { get; set; }
        public int TypeId { get; set; }
        public string RespondedDocuments { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.Guid> RequestedUserID { get; set; }
        public Nullable<System.Guid> RespondedUserID { get; set; }
        public Nullable<System.DateTime> RespondedDate { get; set; }
        public Nullable<bool> MediaDownloaded { get; set; }
        public Nullable<bool> MediaUploaded { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<int> RequestStatusId { get; set; }
        public Nullable<System.DateTime> ReSubmittedDate { get; set; }
        public Nullable<System.Guid> ReSubmittedBy { get; set; }
        public string TypeConstraints { get; set; }
    
        public virtual MSI_MediaRequestResponse MSI_MediaRequestResponse {internal get; set; }
        public virtual MSI_MediaRequestStatus MSI_MediaRequestStatus { internal get; set; }
        public virtual MSI_MediaTypes MSI_MediaTypes { internal get; set; }
    }
}
