//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_Port_SalesTrans_Original
    {
        public int ID { get; set; }
        public string Portfolio_ { get; set; }
        public Nullable<System.DateTime> Cut_OffDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string Lender { get; set; }
        public string Buyer { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<double> SalesBasis { get; set; }
        public Nullable<decimal> FaceValue { get; set; }
        public Nullable<double> C_ofAccts { get; set; }
        public Nullable<double> PutbackTerm_days_ { get; set; }
        public Nullable<System.DateTime> PutbackDeadline { get; set; }
        public string Notes { get; set; }
    }
}
