//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_MediaForm
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CompanyRequesting { get; set; }
        public string Portfolio { get; set; }
        public string OriginalLender { get; set; }
        public string OrigAcct { get; set; }
        public string SSN { get; set; }
        public string AcctName { get; set; }
        public Nullable<bool> IsApplication { get; set; }
        public Nullable<bool> IsAffidavitIssuer { get; set; }
        public Nullable<bool> IsAffidavitSeller { get; set; }
        public Nullable<System.DateTime> StmtsFrom { get; set; }
        public Nullable<System.DateTime> StmtsTo { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CODate { get; set; }
        public string Explanation { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public Nullable<decimal> SellerFee { get; set; }
        public Nullable<System.DateTime> DateSellerPaid { get; set; }
        public Nullable<decimal> OurFee { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateForwarded { get; set; }
        public string MediaTypeReceived { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsUnavailable { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> UnavailableDate { get; set; }
        public string SellerInvoice { get; set; }
        public Nullable<System.DateTime> DatePayRec { get; set; }
        public string BuyerCheck { get; set; }
        public string OurCheck { get; set; }
        public string PIMSAcct { get; set; }
        public string Seller { get; set; }
        public string OrderNumber { get; set; }
        public string OurInvoice { get; set; }
        public string GUID { get; set; }
        public string FileName { get; set; }
        public byte[] FileBinary { get; set; }
        public byte[] FileBinaryImage { get; set; }
    }
}
