//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_Port_InvestmentsTrans
    {
        public int ID { get; set; }
        public string Portfolio_ { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<double> ProfitShare_before { get; set; }
        public Nullable<double> ProfitShare_after { get; set; }
        public Nullable<double> Interest { get; set; }
        public string Inv_AgencyName { get; set; }
        public string Notes { get; set; }
        public string TransType { get; set; }
        public Nullable<bool> IsOriginal { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
