//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_DPSForm
    {
        public int ID { get; set; }
        public string PIMSAcct { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> NetPayment { get; set; }
        public string TransCode { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<int> PmtType { get; set; }
        public Nullable<int> TransSource { get; set; }
        public string Portfolio { get; set; }
        public string AcctName { get; set; }
        public Nullable<System.DateTime> DateRec { get; set; }
        public string CurrentResp { get; set; }
        public string OriginalAcct { get; set; }
        public string OurCheckNumber { get; set; }
        public Nullable<bool> Uploaded { get; set; }
        public string GUID { get; set; }
    }
}
