//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Cascade.Data.Models
{
    public partial class MSI_vwSales
    {
        public string Responsibility { get; set; }
        public string ACCOUNT { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public Nullable<decimal> SalesBasis { get; set; }
        public Nullable<decimal> FaceValue { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
    }
    
}
