//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Cascade.Data.Models
{
    public partial class Port_DPS
    {
        public int ID { get; set; }
        public string PIMSAcct_ { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Net_Payment { get; set; }
        public string TransCode { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<int> PmtType { get; set; }
        public Nullable<int> TransSource { get; set; }
        public string Portfolio_ { get; set; }
        public string AcctName { get; set; }
        public Nullable<System.DateTime> DateRec { get; set; }
        public string CurrentResp { get; set; }
        public string OrigAcct_ { get; set; }
        public string OurCheckNumber { get; set; }
        public Nullable<System.DateTime> Uploaded__y_n_ { get; set; }
    }
    
}
