//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Cascade.Data.Models
{
    public partial class RACCBKRP
    {
        public int BankruptRecordID { get; set; }
        public Nullable<bool> CurrentBKT { get; set; }
        public string Division_ID { get; set; }
        public string Account { get; set; }
        public string Screen { get; set; }
        public string CaseNumber { get; set; }
        public string Chapter { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string DispositionCode { get; set; }
        public string Business { get; set; }
        public string PreFix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string SSN { get; set; }
        public string Address1Filed { get; set; }
        public string Address2Filed { get; set; }
        public string CityFiled { get; set; }
        public string StateFiled { get; set; }
        public string ZipCodeFiled { get; set; }
        public string Zip4Filed { get; set; }
        public string CountyFiled { get; set; }
        public string CountryFiled { get; set; }
        public string Business1 { get; set; }
        public string Business2 { get; set; }
        public string Business3 { get; set; }
        public string DebtorsAddress1 { get; set; }
        public string DebtorsAddress2 { get; set; }
        public string DebtorsCity { get; set; }
        public string DebtorsState { get; set; }
        public string DebtorsZip { get; set; }
        public string DebtorsZip4 { get; set; }
        public string DebtorsCounty { get; set; }
        public string DebtorsCountry { get; set; }
        public string ECOA { get; set; }
        public string LawFirm { get; set; }
        public string AttorneyName { get; set; }
        public string AttorneyAddress1 { get; set; }
        public string AttorneyAddress2 { get; set; }
        public string AttorneyCity { get; set; }
        public string AttorneyState { get; set; }
        public string AttorneyZip { get; set; }
        public string AttorneyPhone { get; set; }
        public string AttorneyFax { get; set; }
        public string Date341 { get; set; }
        public string Time341 { get; set; }
        public string Location341 { get; set; }
        public string Trustee { get; set; }
        public string District { get; set; }
        public string Court { get; set; }
        public string TrusteeAddress1 { get; set; }
        public string TrusteeAddress2 { get; set; }
        public string TrusteeCity { get; set; }
        public string TrusteeState { get; set; }
        public string TrusteeZip { get; set; }
        public string TrusteePhone { get; set; }
        public string TrusteeFax { get; set; }
        public string Judges_Intials { get; set; }
        public string Funds { get; set; }
        public string BarDate { get; set; }
        public string DebtorsPhone { get; set; }
        public string AttorneyLastNameSuffix { get; set; }
        public string AttorneyMiddleInit { get; set; }
        public string AttorneyFirstName { get; set; }
        public string CourtAddress1 { get; set; }
        public string CourtAddress2 { get; set; }
        public string CourtCity { get; set; }
        public string CourtState { get; set; }
        public string CourtZip { get; set; }
        public string CourtPhone { get; set; }
        public Nullable<bool> ECF { get; set; }
        public Nullable<System.DateTime> POCDate { get; set; }
        public Nullable<System.DateTime> POCDeadline { get; set; }
        public string ClaimNumber { get; set; }
        public Nullable<System.DateTime> POCConfirmDate { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<System.DateTime> BKRTDateGranted { get; set; }
    
        public virtual RACCOUNT RACCOUNT { get; set; }
    }
    
}
