//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RINTRATE
    {
        public string CODE { get; set; }
        public string TYPE { get; set; }
        public Nullable<System.DateTime> DATE_STARTED { get; set; }
        public Nullable<System.DateTime> DATE_ENDED { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string COMPOUND_PERIOD { get; set; }
        public string GEN_TRAN_CODE { get; set; }
        public Nullable<decimal> INT_DAYS_PER_YR { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
