//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Cascade.Data.Models
{
    public partial class RPRODCDE
    {
        public RPRODCDE()
        {
            this.RACCOUNTs = new HashSet<RACCOUNT>();
        }
    
        public int ProductID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ACTIVE_YN { get; set; }
        public Nullable<bool> Collateral { get; set; }
        public string UPDATE_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Contact { get; set; }
        public string PortfolioName { get; set; }
        public string PortfolioOwner { get; set; }
        public string AgencyCode { get; set; }
        public Nullable<double> SIFPercent { get; set; }
        public Nullable<bool> GrossNet { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool SaveBankInfo { get; set; }
        public bool SaveCCInfo { get; set; }
    
        public virtual ICollection<RACCOUNT> RACCOUNTs { get; set; }
    }
    
}
