//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Cascade.Data.Models
{
    public partial class RTRANCDE
    {
        public string TRAN_CODE { get; set; }
        public string IS_PAYMENT { get; set; }
        public string CREDIT_DEBIT { get; set; }
        public string DESCR { get; set; }
        public string IS_NSF { get; set; }
        public string IS_ADJUSTMENT { get; set; }
        public string IS_COST { get; set; }
        public Nullable<int> BATCHTYPEID { get; set; }
        public string UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int TranCodeID { get; set; }
    }
    
}
