//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Portfolio
    {
        public double ACCOUNT { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> LAST_PAY_DATE { get; set; }
        public Nullable<double> LAST_PAY_AMT { get; set; }
        public Nullable<double> DaysSinceLastPay { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> PortfolioID { get; set; }
        public string Portfolio { get; set; }
        public Nullable<double> AccruedInterest { get; set; }
        public Nullable<double> TotalInterest { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<double> ZIP_CODE { get; set; }
        public Nullable<double> Statute { get; set; }
        public Nullable<double> DaysRemainingInStat { get; set; }
        public Nullable<System.DateTime> StatuteDate { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public Nullable<double> Closed { get; set; }
        public string WorkStatusDescription { get; set; }
        public string WorkGroup { get; set; }
        public string PortfolioOwner { get; set; }
        public string PortfolioName { get; set; }
    }
}
