//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Cascade.Data.Models
{
    public partial class vw_AddDPSCheck
    {
        public int ID { get; set; }
        public string Portfolio_ { get; set; }
        public string PIMSAcct_ { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateRec { get; set; }
        public string CurrentResp { get; set; }
        public string OurCheckNumber { get; set; }
        public string CheckNumber { get; set; }
        public string Company { get; set; }
    }
    
}
