//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PortfolioCashFlow
    {
        public string Portfolio_ { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string TransType { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public string Company { get; set; }
    }
}
