//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cascade.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PortfolioSummary
    {
        public string Portfolio_ { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<decimal> Face { get; set; }
        public Nullable<double> CostBasis { get; set; }
        public string Lender_FileDescription { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SumOfSalesPrice { get; set; }
        public Nullable<decimal> CashPos { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> Return_on_Capital { get; set; }
        public Nullable<double> irrIRR { get; set; }
    }
}
