//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Cascade.Data.Models
{
    public partial class vw_PortfolioTransactions
    {
        public string Portfolio_ { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public string TransType { get; set; }
        public string Company { get; set; }
        public string Agency { get; set; }
        public string Lender_FileDescription { get; set; }
        public string Seller { get; set; }
    }
    
}
